export const GET_USERS_LIST = "GET_USERS_LIST";
export const SET_USERS_LOADING = "SET_USERS_LOADING";
export const CHANGE_SEARCH_INPUT_VALUE = "CHANGE_SEARCH_INPUT_VALUE";

export const SELECT_USER_NAME = "SELECT_USER_NAME";
export const SET_USER_LOADING = "SET_USER_LOADING";
export const GET_USER = "GET_USER";
export const GET_USER_REPOS = "GET_USER_REPOS";
export const SET_USER_REPOS_LOADING = "SET_USER_REPOS_LOADING";
