export const SET_USER_LOADING = "SET_USER_LOADING";
export const GET_USER = "GET_USER";
export const GET_USER_REPOS = "GET_USER_REPOS";
export const SET_USER_REPOS_LOADING = "SET_USER_REPOS_LOADING";
